# Generated by Django 4.2.4 on 2023-08-15 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.IntegerField()),
                ('deal_name', models.CharField(max_length=155)),
                ('person_id', models.IntegerField()),
                ('person_name', models.CharField(max_length=155)),
                ('person_phone', models.CharField(max_length=25)),
                ('person_email', models.EmailField(max_length=55)),
            ],
            options={
                'indexes': [models.Index(fields=['deal_id', 'deal_name'], name='app_webhook_deal_id_b4445c_idx')],
            },
        ),
    ]
