# Generated by Django 4.2.4 on 2023-08-18 16:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_webhook', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='deals',
            name='app_webhook_deal_id_b4445c_idx',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='deal_id',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='deal_name',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='person_email',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='person_id',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='person_name',
        ),
        migrations.RemoveField(
            model_name='deals',
            name='person_phone',
        ),
        migrations.AddField(
            model_name='deals',
            name='current_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='deals',
            name='current_add_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deals',
            name='current_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deals',
            name='current_org_name',
            field=models.CharField(default='-', max_length=155),
        ),
        migrations.AddField(
            model_name='deals',
            name='current_owner_name',
            field=models.CharField(default='-', max_length=155),
        ),
        migrations.AddField(
            model_name='deals',
            name='current_person_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deals',
            name='current_person_name',
            field=models.CharField(default='-', max_length=155),
        ),
        migrations.AddField(
            model_name='deals',
            name='current_pipeline_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deals',
            name='current_stage_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deals',
            name='current_status',
            field=models.CharField(default='-', max_length=15),
        ),
        migrations.AddField(
            model_name='deals',
            name='current_title',
            field=models.CharField(default='-', max_length=155),
        ),
        migrations.AddField(
            model_name='deals',
            name='current_update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deals',
            name='current_value',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='deals',
            name='current_weighted_value',
            field=models.FloatField(default=0.0),
        ),
    ]
