# Generated by Django 4.2.4 on 2023-08-19 02:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_webhook', '0002_remove_deals_app_webhook_deal_id_b4445c_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_id', models.IntegerField(default=0)),
                ('current_name', models.CharField(default='-', max_length=155)),
                ('current_owner_name', models.CharField(default='-', max_length=155)),
                ('current_open_deals_count', models.IntegerField(default=0)),
                ('current_email', models.CharField(default='-', max_length=55)),
                ('current_phone', models.CharField(default='-', max_length=25)),
                ('current_add_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('current_update_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
