# Generated by Django 4.2.4 on 2023-08-19 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_webhook', '0003_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='deals',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_webhook.person'),
        ),
    ]
