# Generated by Django 4.2.4 on 2023-09-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_webhook', '0005_rename_current_active_deals_current_deal_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='current_person_cnpj',
            field=models.CharField(default='-', max_length=18),
        ),
        migrations.AddField(
            model_name='person',
            name='current_person_cpf',
            field=models.CharField(default='-', max_length=14),
        ),
    ]
